# Generated by Django 4.1 on 2022-08-16 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_passenger'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passenger',
            new_name='Passengers',
        ),
    ]
