# Generated by Django 4.1 on 2022-08-16 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_rename_passenger_passengers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passengers',
            new_name='Passenger',
        ),
    ]
